[versions]
kotlin = "2.1.0"
coroutines = "1.10.1"
serialization = "1.8.0"
dex2jar = "2.4.32"
okhttp = "5.3.0"
multiplatform-settings = "0.8.1"

[libraries]
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

# Quickjs4j
quickjs4j = "io.roastedroot:quickjs4j:0.0.13"
quickjs4j-annotations = "io.roastedroot:quickjs4j-annotations:0.0.13"
quickjs4j-processor = "io.roastedroot:quickjs4j-processor:0.0.13"

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-jdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "coroutines" }

serialization-protobuf = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version.ref = "serialization" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
serialization-json-okio = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json-okio", version.ref = "serialization" }

# Dependency Injection
kodein = "org.kodein.di:kodein-di-conf-jvm:7.11.0"

# Logging
logback = "ch.qos.logback:logback-classic:1.2.11"
kotlinlogging = "io.github.microutils:kotlin-logging:2.1.21"

# ReactiveX
rxjava = "io.reactivex:rxjava:1.3.8"
rxkotlin = "io.reactivex:rxkotlin:1.0.0"

# JSoup
jsoup = "org.jsoup:jsoup:1.21.2"

# Dependency of :AndroidCompat:Config
typesafe_config = "com.typesafe:config:1.4.2"

# dex2jar
asm = "org.ow2.asm:asm:9.8"
dex2jar-translator = { module = "de.femtopedia.dex2jar:dex-translator", version.ref = "dex2jar" }
dex2jar-tools = { module = "de.femtopedia.dex2jar:dex-tools", version.ref = "dex2jar" }

# APK parser
apk-parser = "net.dongliu:apk-parser:2.6.10"

# OkHttp
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okhttp-dns-over-https = { module = "com.squareup.okhttp3:okhttp-dnsoverhttps", version.ref = "okhttp" }
okhttp-brotli = { module = "com.squareup.okhttp3:okhttp-brotli", version.ref = "okhttp" }
okio = "com.squareup.okio:okio:3.3.0"

# injekt-core
injekt-core = { module = "com.github.null2264.injekt:injekt-core", version = "4135455a2a" }

xmlpull = "xmlpull:xmlpull:1.1.3.4a"
apksig = "com.android.tools.build:apksig:8.13.0"
androidx-annotation = "androidx.annotation:annotation:1.3.0"
multiplatform-settings-jvm = { module = "com.russhwolf:multiplatform-settings-jvm", version.ref = "multiplatform-settings" }
multiplatform-settings-serialization-jvm = { module = "com.russhwolf:multiplatform-settings-serialization-jvm", version.ref = "multiplatform-settings" }
icu4j = "com.ibm.icu:icu4j:70.1"

# NanoHTTPD
nanohttpd = "org.nanohttpd:nanohttpd:2.3.1"

# Jackson
jackson-databind = "tools.jackson.core:jackson-databind:3.0.2"
jackson-kotlin = "tools.jackson.module:jackson-module-kotlin:3.0.2"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

# Linter
kotlinter = { id = "org.jmailen.kotlinter", version = "5.0.1" }

# Build config
buildconfig = { id = "com.github.gmazzo.buildconfig", version = "3.0.3" }

# ShadowJar
shadowjar = { id = "com.github.johnrengelman.shadow", version = "7.1.2" }

[bundles]
common = [
    "kotlin-stdlib-jdk8",
    "kotlin-reflect",
    "coroutines-core",
    "coroutines-jdk8",
    "serialization-json",
    "serialization-json-okio",
    "serialization-protobuf",
    "kodein",
    "logback",
    "kotlinlogging",
    "rxjava",
    "rxkotlin",
    "jsoup",
    "typesafe_config",
    "dex2jar-translator",
    "dex2jar-tools",
    "apk-parser",
    "nanohttpd",
    "jackson-databind",
    "jackson-kotlin",
    "injekt-core",
    "quickjs4j",
    "quickjs4j-annotations",
    "quickjs4j-processor"
]
okhttp = [
    "okhttp",
    "okhttp-logging-interceptor",
    "okhttp-dns-over-https",
    "okhttp-brotli",
    "okio"
]

androidcompat-implementation = [
    "multiplatform-settings-jvm",
    "multiplatform-settings-serialization-jvm",
    "icu4j",
]
androidcompat-compileonly = [
    "xmlpull",
    "apksig",
    "androidx-annotation",
]